FROM node:15.12.0 as builder
WORKDIR /app
COPY package.json ./
COPY rollup.config.js ./
RUN npm install
COPY ./ ./
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/public /usr/share/nginx/html