version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "3000:80"

  mysql:
    container_name: mysql
    build: ./mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=chan2461
    volumes:
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
